#!/usr/bin/env Rscript

# Publication release, stage 02 -- contrast manifests.
#
# Produces
#   metadata/primary_contrast_manifest.tsv    exactly 12 rows
#   metadata/secondary_analysis_manifest.tsv  everything that is NOT one of the 12
#
# The 12 primary contrasts are GENERATED by primary_contrast_manifest() in
# R/analysis_labels.R -- the canonical helper -- and never re-encoded by hand here. They
# are then verified against 02_data/animal_level/split/indexComparisons.csv, which is
# what the differential tables were actually split into.
#
# Primary and secondary analyses are kept in separate files on purpose. The historical
# submission mixed a cross-compartment analysis in with the treatment contrasts; a reader
# could not tell which rows were the designed comparisons.

suppressWarnings({
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  here <- if (length(file_arg) == 1L) dirname(sub("^--file=", "", file_arg)) else "07_publication_release"
})
source(file.path(here, "R", "release_utils.R"))
REPO_ROOT <- release_repo_root()
release_source_project_helpers(REPO_ROOT)
source(file.path(REPO_ROOT, "07_publication_release", "R", "release_validation.R"))
release_require("digest")

DATA_ROOT <- release_data_root()
OUT_ROOT <- release_prepare_output_root()
STAGE <- "07_publication_release/02_build_contrast_manifest.R"

release_banner("stage 02 -- contrast manifests")

ANIMAL_ROOT <- file.path(DATA_ROOT, "02_data", "animal_level")
ENRICH_ROOT <- file.path(DATA_ROOT, "03_output", "enrichment",
                         "enrichment_t_rank_validation_20260825")
REVISION_ROOT <- file.path(DATA_ROOT, "03_output", "reviewer_revision_animal_level_20260827")
INFERENTIAL <- file.path(DATA_ROOT, "03_output", "inferential_checks",
                         "final_inferential_checks_20260826")

paths <- list(
  split_index = file.path(ANIMAL_ROOT, "split", "indexComparisons.csv"),
  mapped_index = file.path(ANIMAL_ROOT, "mapped", "indexMappedComparisons.csv"),
  contrast_scope = file.path(ANIMAL_ROOT, "input_gct", "contrast_scope_audit.csv"),
  protigy_manifest = file.path(ANIMAL_ROOT, "input_gct", "protigy_contrast_manifest.csv"),
  animal_metadata = release_path("metadata", "animal_level_sample_metadata.tsv",
                                 create_dir = FALSE)
)
for (nm in names(paths)) release_assert_exists(paths[[nm]], nm)

split_index <- release_read_csv(paths$split_index)
mapped_index <- release_read_csv(paths$mapped_index)
contrast_scope <- release_read_csv(paths$contrast_scope)
animal_level <- release_read_tsv_plain(paths$animal_metadata)

# --------------------------------------------------------------------------------------
# primary contrasts, generated by the canonical helper
# --------------------------------------------------------------------------------------

canonical <- primary_contrast_manifest()
if (nrow(canonical) != RELEASE_DESIGN_INVARIANTS$n_primary_contrasts) {
  stop("primary_contrast_manifest() returned ", nrow(canonical), " rows, expected 12.",
       call. = FALSE)
}

# n per arm, counted from the animal-level metadata rather than asserted as 3.
stratum_n <- table(paste(animal_level$sample_class, animal_level$condition, sep = "\r"))
arm_n <- function(sample_class, condition) {
  key <- paste(sample_class, condition, sep = "\r")
  n <- as.integer(stratum_n[key])
  if (anyNA(n)) stop("No animal-level stratum for ", key, call. = FALSE)
  n
}

INTERPRETATION <- c(
  paired_cno_vs_paired_veh = paste(
    "Chemogenetic (CNO) effect within associatively paired animals:",
    "paired_cno relative to paired_veh. Positive log2FC = higher in paired_cno."),
  paired_veh_vs_unpaired_veh = paste(
    "Pairing-associated (learning) signature under vehicle:",
    "paired_veh relative to unpaired_veh. Positive log2FC = higher in paired_veh.",
    "Because pairing condition was completely associated with collection plate in this",
    "comparison, any collection-plate-associated contribution cannot be distinguished",
    "from a pairing-associated contribution."),
  unpaired_cno_vs_unpaired_veh = paste(
    "Chemogenetic (CNO) effect within unpaired control animals:",
    "unpaired_cno relative to unpaired_veh. Positive log2FC = higher in unpaired_cno.")
)

primary <- data.frame(
  sample_class = canonical$sample_class,
  contrast_family = canonical$contrast_family,
  numerator_condition = canonical$case_condition,
  denominator_condition = canonical$reference_condition,
  numerator_code = canonical$case_code,
  denominator_code = canonical$reference_code,
  numerator_phenotype = canonical$case_phenotype,
  denominator_phenotype = canonical$reference_phenotype,
  canonical_comparison = canonical$canonical_comparison,
  canonical_contrast = canonical$canonical_contrast,
  historical_comparison_alias = canonical$historical_comparison_name,
  n_numerator_animals = mapply(arm_n, canonical$sample_class, canonical$case_condition),
  n_denominator_animals = mapply(arm_n, canonical$sample_class, canonical$reference_condition),
  analysis_unit = "animal",
  primary_or_secondary = "primary",
  statistical_model = "within_sample_class_animal_level_two_sample_moderated_t (ProTigy)",
  gsea_ranking_statistic = "moderated_t",
  interpretation = unname(INTERPRETATION[canonical$contrast_family]),
  stringsAsFactors = FALSE, check.names = FALSE
)

# Attach the canonical artefact locations so each row is self-contained.
primary$differential_statistics_file <- file.path(
  "differential_analysis", "primary_differential_proteins.tsv.gz")
primary$canonical_split_forward_path <- file.path(
  ANIMAL_ROOT, "split", "forward", paste0(primary$canonical_contrast, ".csv"))
primary$canonical_mapped_forward_path <- file.path(
  ANIMAL_ROOT, "mapped", "forward", paste0(primary$canonical_contrast, ".csv"))
primary$canonical_enrichment_dir <- file.path(
  ENRICH_ROOT, "per_comparison", primary$canonical_comparison)

missing_split <- primary$canonical_split_forward_path[!file.exists(primary$canonical_split_forward_path)]
if (length(missing_split)) {
  stop("Canonical split tables missing:\n", paste("  -", missing_split, collapse = "\n"), call. = FALSE)
}
missing_enrich <- primary$canonical_enrichment_dir[!dir.exists(primary$canonical_enrichment_dir)]
if (length(missing_enrich)) {
  stop("Canonical enrichment folders missing:\n",
       paste("  -", missing_enrich, collapse = "\n"), call. = FALSE)
}

# Verify against the split index: same 12 comparisons, same orientation.
if (nrow(split_index) != 12L) {
  stop("indexComparisons.csv has ", nrow(split_index), " rows, expected 12.", call. = FALSE)
}
ordered_primary <- primary[order(primary$canonical_comparison), , drop = FALSE]
ordered_index <- split_index[order(split_index$canonical_comparison), , drop = FALSE]
for (col in c("canonical_comparison", "canonical_contrast", "sample_class",
              "numerator_condition", "denominator_condition")) {
  if (!identical(as.character(ordered_primary[[col]]), as.character(ordered_index[[col]]))) {
    stop("Generated primary manifest disagrees with indexComparisons.csv on ", col, call. = FALSE)
  }
}
if (!identical(sort(as.character(ordered_primary$historical_comparison_alias)),
               sort(as.character(ordered_index$historical_comparison_alias)))) {
  stop("Historical comparison aliases disagree with indexComparisons.csv.", call. = FALSE)
}
if (nrow(mapped_index) != 12L) {
  stop("indexMappedComparisons.csv has ", nrow(mapped_index), " rows, expected 12.", call. = FALSE)
}
release_log("  12 primary contrasts generated and verified against the canonical split index")

if (!all(primary$n_numerator_animals == 3L) || !all(primary$n_denominator_animals == 3L)) {
  stop("Primary contrasts are not all 3 vs 3 animals.", call. = FALSE)
}

primary <- primary[order(match(primary$sample_class, sample_classes),
                          primary$contrast_family), , drop = FALSE]
rownames(primary) <- NULL

# --------------------------------------------------------------------------------------
# secondary analyses -- deliberately a separate table
# --------------------------------------------------------------------------------------

sec <- function(analysis_id, analysis_name, analysis_type, comparisons, condition_scope,
                analysis_unit, statistical_model, ranking_statistic, n_per_group,
                canonical_source, generating_script, interpretation, caveat,
                in_primary_manifest = "FALSE") {
  data.frame(
    analysis_id = analysis_id, analysis_name = analysis_name, analysis_type = analysis_type,
    comparisons = comparisons, condition_scope = condition_scope,
    analysis_unit = analysis_unit, statistical_model = statistical_model,
    ranking_statistic = ranking_statistic, n_per_group = n_per_group,
    primary_or_secondary = "secondary",
    included_in_primary_contrast_manifest = in_primary_manifest,
    canonical_source = canonical_source, generating_script = generating_script,
    interpretation = interpretation, caveat = caveat,
    stringsAsFactors = FALSE, check.names = FALSE)
}

secondary <- rbind(
  sec("supp_E_cross_compartment_paired",
      "Supplementary E -- cross-compartment cellular identities (secondary paired model)",
      "cross_compartment_within_animal_paired_differential_and_GSEA",
      "neuropil_vs_neuron;cfos_vs_neuron;mcherry_vs_cfos;mcherry_vs_neuron",
      "paired_veh only",
      "animal (within-animal paired; AnimalID as a fixed blocking effect)",
      "limma ~ 0 + sample_class + AnimalID; full rank 6/6; residual df 6; eBayes df.total 27.435",
      "moderated_t from the paired model",
      "3 animals, 4 compartments each",
      file.path(REVISION_ROOT, "full_regenerated", "cross_compartment", "SuppE_secondary_paired"),
      "06_manuscript_figure_revision/18_suppE_secondary_paired_model.R",
      paste("Shows that the dissected fractions have biologically coherent relative",
            "identities. NOT a treatment effect and NOT one of the 12 primary contrasts."),
      paste("Both arms of every comparison come from the SAME three animals (100% animal",
            "overlap), so an unpaired two-sample test would be invalid. n = 3 animals and",
            "residual df 6 before empirical-Bayes moderation: low power; inference must be",
            "treated cautiously.")),
  sec("gsea_log2fc_rank_sensitivity",
      "GSEA ranked by log2FC (sensitivity analysis)",
      "gene_set_enrichment_sensitivity",
      "all 12 primary comparisons",
      "same as the primary contrasts",
      "animal",
      "no model fitted; re-ranking of the canonical animal-level statistics",
      "log2fc",
      "3 vs 3 animals",
      file.path(ENRICH_ROOT, "per_comparison", "<comparison>",
                "GSEA_{GO_BP,KEGG}_log2fc_sensitivity.csv"),
      "04_differential_expression_enrichment/01_clusterProfiler.r",
      paste("Robustness check on the choice of ranking statistic. The CANONICAL GSEA ranks",
            "by the moderated t statistic; these rows exist only as sensitivity."),
      paste("Must never be reported as the primary enrichment result. Carried in the",
            "release with analysis_role = sensitivity and in a separate file.")),
  sec("posthoc_pairing_x_cno_interaction",
      "Post-hoc Pairing x CNO interaction",
      "posthoc_interaction_protein_and_GSEA",
      "Pairing x Treatment interaction within sample class",
      "all four conditions",
      "animal",
      "post-hoc interaction contrast on the animal-level matrix",
      "moderated_t",
      "3 animals per cell",
      file.path(INFERENTIAL, "posthoc_pairing_x_cno_interaction"),
      "inferential-checks stage (03_output/inferential_checks/final_inferential_checks_20260826)",
      paste("Asks whether the CNO effect differs between paired and unpaired animals."),
      paste("Post-hoc and n = 3 per cell. Because collection plate and Pairing are",
            "associated, a Plate x Treatment contribution cannot be distinguished from a",
            "Pairing x Treatment one. Neither has been demonstrated.")),
  sec("ewce_baseline_cell_type_identity",
      "EWCE baseline cell-type identity per condition",
      "cell_type_enrichment_of_abundant_protein_lists",
      "4 sample classes x 4 conditions (not a differential contrast)",
      "all four conditions",
      "animal",
      "EWCE bootstrap enrichment against a measured-proteome background",
      "protein abundance rank (most abundant top-N)",
      "3 animals per condition per sample class",
      file.path(DATA_ROOT, "03_output", "ewce",
                "EWCE_Results_animal_level_validation_20260825"),
      "05_celltype_enrichment_EWCE/01_EWCE.r",
      paste("Descriptive cell-type identity of each dissected fraction.",
            "Source of Supplementary C."),
      "Not a treatment comparison; AnalysisType = Baseline, Direction = abundant."),
  sec("excluded_paired_cno_vs_unpaired_cno",
      "paired_cno vs unpaired_cno (candidate contrast, excluded)",
      "candidate_contrast_not_analysed",
      "paired_cno vs unpaired_cno within sample class",
      "cno only",
      "animal",
      "not fitted",
      "not applicable",
      "would be 3 vs 3 animals",
      paths$contrast_scope,
      "not generated",
      paste("Present only in generic all-pairwise historical outputs; absent from the",
            "organised current downstream consumers."),
      "Recorded as a deliberate exclusion: do not add without a verified scientific consumer."),
  sec("excluded_cross_sample_class_two_sample",
      "Cross-sample-class comparison by ordinary independent two-sample test (excluded)",
      "candidate_contrast_not_analysed",
      "any sample_class vs sample_class at a fixed condition",
      "any single condition",
      "would be animal, but the arms are not independent",
      "not fitted",
      "not applicable",
      "3 animals contributing to BOTH arms",
      paths$contrast_scope,
      "not generated",
      paste("Historical baseline profiling used ordinary independent two-sample tests here."),
      paste("Requires paired/animal-aware modelling; an ordinary independent two-sample",
            "test is invalid because both arms come from the same animals. Superseded by",
            "the supp_E_cross_compartment_paired secondary model."))
)
rownames(secondary) <- NULL

# The canonical contrast-scope audit must still agree about what is primary.
scope_true <- contrast_scope$candidate_contrast[
  toupper(as.character(contrast_scope$include_in_primary_contrast_manifest)) == "TRUE"]
if (!identical(sort(unique(as.character(scope_true))), sort(unique(primary$contrast_family)))) {
  stop("contrast_scope_audit.csv no longer agrees with the three primary contrast families.",
       call. = FALSE)
}
release_log("  ", nrow(secondary), " secondary / excluded analyses recorded separately")

# --------------------------------------------------------------------------------------
# write
# --------------------------------------------------------------------------------------

sources <- c(paths$split_index, paths$mapped_index, paths$contrast_scope,
             paths$protigy_manifest,
             file.path(REPO_ROOT, "R", "analysis_labels.R"))
hashes <- vapply(sources, release_sha256, character(1), USE.NAMES = FALSE)

w1 <- release_write_table(primary, release_path("metadata", "primary_contrast_manifest.tsv"))
release_register("metadata/primary_contrast_manifest.tsv",
                 "the 12 primary within-sample-class animal-level contrasts",
                 sources, hashes, STAGE, "tsv")

w2 <- release_write_table(secondary, release_path("metadata", "secondary_analysis_manifest.tsv"))
release_register("metadata/secondary_analysis_manifest.tsv",
                 "secondary and deliberately excluded analyses, kept out of the primary table",
                 sources, hashes, STAGE, "tsv")

release_log("  wrote primary_contrast_manifest.tsv (", w1$rows, "x", w1$cols, ")")
release_log("  wrote secondary_analysis_manifest.tsv (", w2$rows, "x", w2$cols, ")")
release_log("stage 02 complete")
