#!/usr/bin/env Rscript

# Publication release, stage 11 -- README_DATA.md and the data dictionary.
#
# Produces
#   README_DATA.md                 the human entry point to the package
#   metadata/data_dictionary.tsv   every column of every release table, described
#
# The dictionary is generated by walking the tables that exist and looking each column up
# in DESCRIPTIONS. A column with no entry is a hard error, so the dictionary cannot quietly
# fall behind a table that gained a field.
#
# Wording constraints enforced here (release_check_forbidden_wording):
#   the collection-plate sentence must appear verbatim, and the phrases "plate artefact",
#   "confirmed batch confound", "driven by plate" and "technical plate effect" must not
#   appear anywhere in the generated prose.

suppressWarnings({
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  here <- if (length(file_arg) == 1L) dirname(sub("^--file=", "", file_arg)) else "07_publication_release"
})
source(file.path(here, "R", "release_utils.R"))
REPO_ROOT <- release_repo_root()
release_source_project_helpers(REPO_ROOT)
source(file.path(REPO_ROOT, "07_publication_release", "R", "release_validation.R"))
release_require("digest")

DATA_ROOT <- release_data_root()
OUT_ROOT <- release_prepare_output_root()
STAGE <- "07_publication_release/11_build_readme_and_dictionary.R"

release_banner("stage 11 -- README_DATA and data dictionary")

PLATE_SENTENCE <- paste(
  "Because pairing condition was completely associated with collection plate in the",
  "paired-vehicle versus unpaired-vehicle comparison, any collection-plate-associated",
  "contribution cannot be distinguished from a pairing-associated contribution.")
NO_BATCH_SENTENCE <- paste(
  "No downstream proteomics batch effect attributable to collection plate has been",
  "demonstrated.")
FORBIDDEN_WORDING <- c("plate artefact", "plate artifact", "confirmed batch confound",
                       "driven by plate", "technical plate effect")

release_check_forbidden_wording <- function(lines) {
  flat <- tolower(paste(lines, collapse = " "))
  hits <- FORBIDDEN_WORDING[vapply(FORBIDDEN_WORDING,
                                   function(p) grepl(tolower(p), flat, fixed = TRUE),
                                   logical(1))]
  if (length(hits)) {
    stop("Forbidden collection-plate wording in generated prose: ",
         paste(hits, collapse = ", "), call. = FALSE)
  }
  invisible(TRUE)
}

rel <- function(...) release_path(..., create_dir = FALSE)
read_release <- function(path) {
  if (grepl("[.]gz$", path)) {
    read.delim(gzfile(path), sep = "\t", quote = "", stringsAsFactors = FALSE,
               check.names = FALSE, nrows = 5L)
  } else {
    read.delim(path, sep = "\t", quote = "", stringsAsFactors = FALSE, check.names = FALSE,
               nrows = 5L)
  }
}

diff_summary <- read.delim(rel("differential_analysis", "primary_differential_summary.tsv"),
                           sep = "\t", quote = "", stringsAsFactors = FALSE, check.names = FALSE)
discrepancy <- read.delim(rel("metadata", "sample_class_source_discrepancy.tsv"), sep = "\t",
                          quote = "", stringsAsFactors = FALSE, check.names = FALSE)
pride_readiness <- read.delim(rel("pride", "pride_readiness.tsv"), sep = "\t", quote = "",
                              stringsAsFactors = FALSE, check.names = FALSE)
pride_status <- pride_readiness$value[pride_readiness$key == "pride_status"]
n_required_missing <- pride_readiness$value[pride_readiness$key == "n_sdrf_required_missing"]

# --------------------------------------------------------------------------------------
# column descriptions
# --------------------------------------------------------------------------------------

DESCRIPTIONS <- c(
  # identity / design
  sample_id = "Canonical measurement identifier. This string IS the acquisition run name and is also the column name in the measurement-level abundance matrix.",
  acquisition_run_name = "Same value as sample_id, named explicitly to make its origin unambiguous.",
  raw_file_basename = "Original acquisition file name, `<run>.d`. Proven: basename of the sample_annotation.xlsx Name column with the .d suffix removed equals sample_id for all 96 runs.",
  raw_file_original_path = "Verbatim acquisition-machine path recorded at search time, e.g. D:\\Proteomics\\Fabian\\Tobias\\<run>.d.",
  raw_file_extension = "Acquisition file extension. `.d` is a vendor-specific acquisition directory format. It identifies a vendor family, not an instrument model.",
  AnimalID = "Animal identifier. 12 animals: C11 C12 C14 C25 C26 C27 C33f C34f C45f C46 C47 C510.",
  hemisphere = "Left or Right. The anatomical side the fraction was taken from.",
  hemisphere_evidence_source = "How hemisphere was established. `explicit_evidence` = the _left/_right suffix on the annotation label, cross-checked against the numeric ReplicateGroup.",
  historical_hemisphere_label = "Legacy annotation label carrying the explicit side, e.g. cFosN_left.",
  legacy_replicate_group = "Legacy numeric hemisphere encoding: 1 = Left, 2 = Right. Retained for traceability.",
  sample_class = "Dissected/labelled fraction: mcherry, neuropil, cfos or neuron.",
  sample_class_historical_alias = "Historical filename alias. `neuropil` was written `bg` (from background) in older filenames; it is a tissue compartment, not a negative control or a blank.",
  sample_class_historical_group_label = "Legacy group label from the annotation workbook: cFosN, Background, mCherryN, Neuron.",
  sample_class_annotation_source = "Sample class as independently recorded in sample_annotation.xlsx (group_label), normalised to the canonical vocabulary.",
  sample_class_plate_layout_implied = "Sample class implied by the autosampler well row letter, using the layout that 90 of the 96 measurements follow (A/E cfos, B/F neuropil, C/G mcherry, D/H neuron).",
  sample_class_corroborated = "TRUE when the sample class used by the analysis agrees with BOTH independent sources. FALSE marks an unresolved discrepancy; see metadata/sample_class_source_discrepancy.tsv.",
  sample_class_used_by_analysis = "The sample class the validated analysis actually used (from sample_info.xlsx), i.e. the class this measurement was averaged under.",
  sample_class_sample_annotation_xlsx = "The sample class recorded independently in sample_annotation.xlsx.",
  animal_level_unit_affected = "The animal-level unit this measurement was averaged into, and which is therefore affected by the discrepancy.",
  condition_code = "Numeric condition code: 1 = paired_cno, 2 = paired_veh, 3 = unpaired_cno, 4 = unpaired_veh.",
  condition = "Condition label: paired_cno, paired_veh, unpaired_cno or unpaired_veh.",
  pairing_status = "paired or unpaired, decomposed from condition.",
  treatment = "cno or veh, decomposed from condition. Tokens are the project's literal condition coding.",
  collection_plate = "Plate1 or Plate2: which plate the sample was collected onto. NOT a proteomics preparation, digestion, LC-MS, acquisition or instrument batch.",
  plate_sample_number = "Sample number token from the acquisition run name, N01..N96.",
  injection_index = "Numeric running index 1..96 parsed from the plate sample number.",
  plate_set_token = "Set token from the acquisition run name (S4 or S5).",
  well_position = "Well position token from the acquisition run name, e.g. A1, H7.",
  acquisition_run_trailing_id = "Trailing numeric identifier in the acquisition run name, e.g. 8782.",
  instrument_alias_token = "Local instrument alias from the acquisition run name (`Olive`). NOT an instrument model.",
  instrument_model = "Instrument model. EMPTY: not recorded anywhere in the project. Deliberately not inferred.",
  acquisition_date = "Acquisition date in ISO form, derived from the run-name date token. All 96 runs carry 2024-12-17.",
  acquisition_date_token = "Verbatim date token from the acquisition run name.",
  lc_and_method_token = "Verbatim LC/method token from the acquisition run name. Preserved undecoded; it is an operator label, not a documented acquisition method.",
  analysis_unit_primary = "The unit of inference for this dataset: always `animal`.",
  included_in_animal_level = "TRUE if this measurement contributed to an animal-level unit. All 96 did.",
  animal_level_sample_id = "The animal-level column this measurement was averaged into, e.g. C11_cfos.",
  measurement_level_matrix_column = "Column name of this measurement in the measurement-level abundance matrix.",
  source_assignment_status = "Assignment outcome recorded by the aggregation stage, e.g. included_in_primary.",
  legacy_sample_number = "Legacy sampleNumber field from sample_info.xlsx.",
  legacy_shortname = "Legacy shortname field from sample_info.xlsx.",
  legacy_group2_hemisphere_coded = "Legacy `group2` field. WARNING: its numeric suffix is the ReplicateGroup (hemisphere), NOT the condition code. `celltype_ExpGroup` was the condition-coded field.",
  # animal-level
  n_hemisphere_measurements = "Number of hemisphere measurements averaged into this animal-level unit. Always 2.",
  hemispheres_present = "Semicolon-separated hemispheres contributing to this unit. Always Left;Right.",
  source_sample_ids = "Semicolon-separated acquisition run names averaged into this unit.",
  source_raw_file_basenames = "Semicolon-separated original `.d` acquisition file names for this unit.",
  left_source_sample = "Acquisition run name of the left-hemisphere measurement.",
  right_source_sample = "Acquisition run name of the right-hemisphere measurement.",
  animal_level_column_name = "Column name of this unit in the animal-level abundance matrix.",
  phenotype_within_unit = "sample_class and condition concatenated; the grouping ProTigy tested on.",
  aggregation_policy = "How the two hemispheres were combined: equal-weight mean on the existing imputed log2 values, with no further transformation.",
  analysis_unit = "The unit of inference for the row: `animal`.",
  # metadata field provenance
  field = "Metadata field being described.",
  status = "Field status: KNOWN_VERIFIED, KNOWN_BUT_NEEDS_STANDARDIZATION, MISSING_RECOVERABLE, MISSING_UNKNOWN or NOT_APPLICABLE.",
  current_source = "File that currently holds the field, or NONE.",
  evidence = "How the status was established.",
  note = "Additional caveat or clarification.",
  # contrasts
  contrast_family = "One of paired_cno_vs_paired_veh, paired_veh_vs_unpaired_veh, unpaired_cno_vs_unpaired_veh.",
  numerator_condition = "Condition in the numerator. Positive log2FC means higher in this condition.",
  denominator_condition = "Condition in the denominator.",
  numerator_code = "Condition code of the numerator arm.",
  denominator_code = "Condition code of the denominator arm.",
  numerator_phenotype = "sample_class and numerator condition concatenated.",
  denominator_phenotype = "sample_class and denominator condition concatenated.",
  canonical_comparison = "Canonical comparison key, `<numerator_phenotype>_over_<denominator_phenotype>`. The join key across differential, enrichment and EWCE tables.",
  canonical_contrast = "Canonical contrast name, `<numerator_phenotype>_vs_<denominator_phenotype>`. Used for the canonical file names.",
  historical_comparison_alias = "Historical short name for the comparison, e.g. bg2_bg4 for neuropil paired_veh vs unpaired_veh.",
  n_numerator_animals = "Number of independent animals in the numerator arm. Always 3.",
  n_denominator_animals = "Number of independent animals in the denominator arm. Always 3.",
  primary_or_secondary = "Whether the row belongs to the 12 primary contrasts or to a secondary analysis.",
  statistical_model = "The model actually fitted for this comparison.",
  gsea_ranking_statistic = "Statistic the canonical GSEA ranked by: the moderated t.",
  interpretation = "What the comparison means, including any identifiability caveat.",
  differential_statistics_file = "Release file holding the per-protein statistics for this comparison.",
  canonical_split_forward_path = "Canonical differential table this comparison was read from.",
  canonical_mapped_forward_path = "Canonical identifier-mapped table for this comparison.",
  canonical_enrichment_dir = "Canonical enrichment output folder for this comparison.",
  # secondary manifest
  analysis_id = "Stable identifier for the secondary or excluded analysis.",
  analysis_name = "Human-readable name of the analysis.",
  analysis_type = "What kind of analysis it is.",
  comparisons = "Comparisons the analysis covers.",
  condition_scope = "Conditions the analysis is restricted to.",
  ranking_statistic = "Statistic used for ranking, where applicable.",
  n_per_group = "Sample size per arm.",
  included_in_primary_contrast_manifest = "Always FALSE here; these rows are deliberately excluded from the primary table.",
  canonical_source = "Canonical output location for this analysis.",
  generating_script = "Script that produced the analysis, where one exists.",
  caveat = "The limitation a reader must carry when reading this analysis.",
  # features
  protein_group_id = "Protein-group identifier: UniProt ENTRY NAME(s), semicolon-separated for multi-protein groups, e.g. MFA1A_MOUSE;MFA1B_MOUSE. This is the row identifier of every abundance and statistics table.",
  protein_group_uniprot_accessions = "All UniProt accessions in the protein group, semicolon-separated, from the search output.",
  uniprot_accession = "UniProt accession of the leading (master) protein in the group.",
  gene_symbol = "Resolved gene symbol for the leading protein. Never a UniProt identifier.",
  gene_symbols_in_group = "All gene symbols in the protein group, semicolon-separated, as reported by the search output.",
  protein_description = "Protein description from the search output (DIA-NN First.Protein.Description).",
  n_proteins_in_group = "Number of proteins in the group.",
  is_protein_group = "TRUE if the group contains more than one protein.",
  id_mapping_status = "mapped or unmapped. 5327 of 5349 map; the 22 unmapped are non-mouse contaminant identifiers.",
  id_mapping_strategy = "Which mapping strategy resolved the identifier.",
  id_mapping_multi_protein = "Whether the mapping had to choose a leading protein from a group.",
  source_matrix_row_index = "Row index in the canonical differential table, for traceability.",
  source_matrix_description_field = "Verbatim value of the source matrix `Description` field. NOTE: despite its name this field holds GENE SYMBOLS, not a protein description. Retained only for traceability.",
  id_mapping_reference_file = "Reference database used for identifier mapping.",
  id_mapping_reference_version = "Version encoded in the reference file, if any.",
  id_mapping_reference_snapshot_date_utc = "Date the reference database snapshot was taken.",
  id_mapping_reference_sha256 = "SHA256 of the reference database file.",
  # differential
  source_matrix_gene_symbols = "Verbatim `Description` value from the canonical differential table; holds gene symbols, not a description.",
  effect_size_sd_units = "Difference of group means (numerator minus denominator) on a per-protein standardised scale, i.e. a standardised mean difference in units of per-protein standard deviation. NOT a log2 fold change, despite being named logFC by ProTigy and log2fc in the canonical split tables. Positive means higher in the numerator condition.",
  effect_size_units = "Units of effect_size_sd_units: per-protein standard deviation.",
  effect_size_definition = "Full statement of what the effect size is and is not. Carried once per comparison in the summary table rather than repeated on every protein row.",
  effect_size_source_column = "The column name this value carries in the canonical source tables.",
  average_standardized_abundance = "Average value across the arms on the standardised scale (limma AveExpr). It is approximately 0 for every protein, which is what a per-protein standardised input implies.",
  moderated_t = "Moderated t statistic. The canonical GSEA ranking statistic.",
  P.Value = "Raw p-value from the moderated t test.",
  adj.P.Val = "Benjamini-Hochberg adjusted p-value.",
  B_log_odds = "Log-odds of differential abundance (limma B statistic).",
  neg_log10_P_value = "-log10 of the raw p-value, as recorded by the canonical analysis.",
  signed_neg_log10_P_value = "-log10 p-value signed by the direction of change. Rounded to 4 decimals in the canonical source.",
  significant_fdr_0_05 = "Canonical significance flag, adj.P.Val < 0.05. Copied, not recomputed.",
  n_proteins_tested = "Protein groups tested in this comparison (all 5349).",
  n_significant_fdr_0_05 = "Protein groups at FDR < 0.05 over all tested rows.",
  n_significant_higher_in_numerator = "Significant protein groups with positive log2FC.",
  n_significant_higher_in_denominator = "Significant protein groups with negative log2FC.",
  n_proteins_tested_mapped_only = "Protein groups tested that carry a mouse identifier (5327).",
  n_significant_fdr_0_05_mapped_only = "Significant protein groups restricted to mapped identifiers. This is the count the manuscript figures report.",
  n_significant_higher_in_numerator_mapped_only = "Significant, positive log2FC, mapped identifiers only.",
  n_significant_higher_in_denominator_mapped_only = "Significant, negative log2FC, mapped identifiers only.",
  significance_definition = "How the canonical significance flag is defined.",
  canonical_source_path = "Canonical file the statistics were read from.",
  canonical_source_sha256 = "SHA256 of that canonical file.",
  # enrichment
  analysis = "Analysis type: GSEA, ORA or EWCE.",
  ontology = "Gene-set collection: GO_BP or KEGG.",
  query_list = "For ORA, which query list the terms were tested against.",
  term_id = "Gene-set identifier (GO or KEGG).",
  term_name = "Gene-set name.",
  set_size = "Number of genes from the ranked list in the gene set (GSEA only).",
  enrichment_score = "GSEA enrichment score.",
  NES = "GSEA normalised enrichment score. Positive means enriched toward the numerator condition.",
  p_value = "Raw p-value.",
  adjusted_p_value = "Benjamini-Hochberg adjusted p-value. The canonical run used pvalue_cutoff = 1, so these tables hold ALL tested terms; filter here.",
  q_value = "q-value as reported by clusterProfiler.",
  gene_count = "Number of query genes annotated to the term (ORA only).",
  gene_ratio = "Query genes in term over query genes tested (ORA only).",
  background_ratio = "Background genes in term over background size (ORA only).",
  fold_enrichment = "Fold enrichment (ORA only).",
  rich_factor = "Rich factor (ORA only).",
  z_score = "z-score (ORA only).",
  rank_at_max = "Rank position at which the GSEA enrichment score is maximal.",
  leading_edge = "GSEA leading-edge summary string (tags/list/signal).",
  core_enrichment = "Gene members. For GSEA the leading-edge subset; for ORA the query genes annotated to the term. See core_enrichment_definition.",
  core_enrichment_definition = "States precisely what core_enrichment holds for this row type.",
  n_core_enrichment_genes = "Count of members in core_enrichment.",
  direction = "Direction of the result, expressed relative to the named conditions.",
  rank_statistic = "Statistic the ranked list was ordered by: moderated_t (canonical), log2fc (sensitivity), or not_applicable (ORA).",
  rank_source_column = "Column of the differential table used as the ranking statistic.",
  analysis_role = "canonical, sensitivity, or alternative_query_list. Canonical and sensitivity rows must never be pooled.",
  gene_identifier_type = "Identifier namespace of the gene members: UNIPROT.",
  ora_universe_definition = "The background universe used for ORA.",
  # EWCE
  ewce_analysis_type = "Baseline (per-condition abundant protein lists) or Differential (per-contrast up/down lists).",
  protein_list_definition = "Which protein list the cell-type enrichment was computed on.",
  cell_type = "Cell type from the reference cell-type dataset.",
  annotation_level = "Cell-type annotation level (1 or 2). The primary setting is 2.",
  top_n = "Size of the protein list tested. The primary setting is 250.",
  n_hits = "Number of proteins in the tested list.",
  n_background = "Size of the measured-proteome background (4859).",
  fold_change = "EWCE fold change relative to the bootstrap null.",
  sd_from_mean = "Standard deviations from the bootstrap null mean.",
  adjusted_p_value_within_target = "FDR-adjusted p-value within the target list.",
  adjusted_p_value_global = "FDR-adjusted p-value across all tests. This is the significance criterion used.",
  significant_global_fdr_0_05 = "TRUE if globally FDR-significant.",
  ewce_direction = "Direction of the EWCE effect as reported by the run.",
  bootstrap_replicates = "Number of bootstrap replicates (10000).",
  is_primary_setting = "TRUE for the primary setting (top-N 250, annotation level 2).",
  # coverage / parameters
  rows_exported = "Rows this release exports for the analysis block.",
  term_count_recorded_by_run = "Term count the canonical run recorded for the same block.",
  agrees_with_run_record = "TRUE when the exported row count equals the canonical record.",
  parameter = "Parameter name.",
  value = "Parameter value.",
  stage = "Analysis stage the parameter belongs to.",
  recorded_by = "Artefact that records the value.",
  evidence_path = "Path to the artefact that records the value.",
  evidence_sha256 = "SHA256 of that artefact.",
  applies_to_stage = "Analysis stage the version applies to.",
  notes = "Additional caveat or clarification.",
  category = "Kind of component: language, R package, external application, instrument, reference database.",
  component = "Software, database or instrument component.",
  version = "Exact version, or UNKNOWN where no version is recorded.",
  # figures
  figure = "Figure the panel belongs to.",
  panel = "Panel letter.",
  panel_label = "Short human label for the panel.",
  panel_title = "Panel title as it appears in the manuscript.",
  source_table = "Release table the panel values can be reproduced from.",
  source_rows_filter = "Row filter to apply to that table to obtain the panel data.",
  statistical_unit = "Unit the revised panel is computed on.",
  original_statistical_unit = "Unit the original panel was computed on.",
  corrected_source_script = "Script that regenerated the panel at animal level.",
  final_revision_script = "Repository snapshot of the script that is the last word for this panel.",
  revision_status = "Outcome of the revision for this panel.",
  displayed_statistics_changed = "Whether the numbers shown on the panel changed.",
  biological_interpretation_changed = "Whether the biological reading of the panel changed.",
  key_numbers_original = "Key numbers on the original panel.",
  key_numbers_revised = "Key numbers on the revised panel.",
  panel_source_data_release_path = "Where the panel source data sits in this release.",
  panel_source_data_original_filename = "Original filename of the panel source data in the canonical revision output.",
  panel_source_data_canonical_path = "Canonical path the panel source data was copied from.",
  panel_source_data_sha256 = "SHA256 of the panel source data.",
  interpretation_note = "What a reader must know to read this panel correctly.",
  # workbook
  sheet = "Workbook sheet name.",
  n_rows = "Rows on the sheet.",
  n_columns = "Columns on the sheet.",
  columns = "Semicolon-separated column names on the sheet.",
  # SDRF
  sdrf_field = "SDRF-Proteomics column, or a non-column deposition requirement.",
  sdrf_requirement = "Whether the field is required or optional for an SDRF submission.",
  value_or_reason = "The value used, or a short reason when the field is missing.",
  why_missing = "Why the field could not be populated.",
  likely_source = "The document or party that would supply the value.",
  required_before_submission = "Whether the field must be filled before PRIDE submission.",
  key = "Name of the reported quantity.",
  # lineage
  artifact_id = "Stable identifier for the artefact within the lineage.",
  artifact_type = "What kind of artefact it is.",
  path_or_release_filename = "Where the artefact lives, or its name in this release.",
  parent_artifact = "Semicolon-separated artifact_id(s) this artefact was derived from.",
  processing_stage = "The operation that produced this artefact. UNRESOLVED when it cannot be proven.",
  software = "Software that performed the step.",
  software_version = "Version of that software, or UNKNOWN.",
  sha256 = "SHA256 of the artefact, where a single file could be hashed.",
  canonical = "Whether this artefact is the canonical one for its stage.",
  # manifest
  relative_path = "Path of the file relative to the release root.",
  file_role = "What the file is for.",
  format = "File format.",
  rows_if_tabular = "Row count for tabular files.",
  columns_if_tabular = "Column count for tabular files.",
  source_artifact = "Semicolon-separated canonical artefact(s) the file was derived from.",
  generated_by = "Release script that produced the file.",
  git_commit = "Repository commit the release was built from.",
  timestamp_utc = "UTC time the file was described.",
  bytes = "File size in bytes.",
  # dictionary itself
  table = "Release file the column belongs to.",
  column = "Column name.",
  description = "What the column holds.",
  # checks
  check = "Name of the validation contract.",
  pass = "Whether the contract holds."
)

# --------------------------------------------------------------------------------------
# build the dictionary
# --------------------------------------------------------------------------------------

TABLES <- c(
  "metadata/sample_metadata.tsv", "metadata/animal_level_sample_metadata.tsv",
  "metadata/metadata_field_provenance.tsv", "metadata/sample_class_source_discrepancy.tsv",
  "metadata/primary_contrast_manifest.tsv", "metadata/secondary_analysis_manifest.tsv",
  "processed_data/protein_abundance_measurement_level.tsv.gz",
  "processed_data/protein_abundance_animal_level.tsv.gz",
  "processed_data/protein_feature_annotation.tsv.gz",
  "differential_analysis/primary_differential_proteins.tsv.gz",
  "differential_analysis/primary_differential_summary.tsv",
  "enrichment/primary_GSEA_GO_BP.tsv.gz", "enrichment/primary_GSEA_KEGG.tsv.gz",
  "enrichment/primary_ORA_GO_BP.tsv.gz", "enrichment/GSEA_log2FC_sensitivity.tsv.gz",
  "enrichment/primary_EWCE.tsv.gz", "enrichment/enrichment_coverage.tsv",
  "enrichment/enrichment_run_parameters.tsv",
  "editor_source_data/figure_source_map.tsv",
  "editor_source_data/workbook_sheet_inventory.tsv",
  "pride/sdrf.tsv", "pride/sdrf_field_status.tsv", "pride/pride_readiness.tsv",
  "provenance/data_lineage.tsv", "provenance/software_versions.tsv",
  "provenance/analysis_parameters.tsv"
)

# The two abundance matrices are wide: one column per sample. Describing 144 sample
# columns individually would bury the dictionary, so they get one generic row each.
WIDE <- c("processed_data/protein_abundance_measurement_level.tsv.gz",
          "processed_data/protein_abundance_animal_level.tsv.gz")
WIDE_NOTE <- c(
  "processed_data/protein_abundance_measurement_level.tsv.gz" =
    "One column per acquisition run, named by the acquisition run name (see metadata/sample_metadata.tsv, column sample_id). Values are processed log2 protein abundance: filtered, median-centred, imputed and PCA-adjusted. NOT raw MS data.",
  "processed_data/protein_abundance_animal_level.tsv.gz" =
    "One column per animal-level unit, named `<AnimalID>_<sample_class>` (see metadata/animal_level_sample_metadata.tsv, column animal_level_column_name). Values are the equal-weight mean of the Left and Right measurements on the existing log2 scale.")

# SDRF columns are ontology-style names already documented field by field in
# pride/sdrf_field_status.tsv. Sourcing their definitions from that table keeps one
# description per field instead of two that can drift apart.
sdrf_status <- read.delim(rel("pride", "sdrf_field_status.tsv"), sep = "\t", quote = "",
                          stringsAsFactors = FALSE, check.names = FALSE)
sdrf_description <- function(cn) {
  hit <- sdrf_status[sdrf_status$sdrf_field == cn, , drop = FALSE]
  if (!nrow(hit)) return(NA_character_)
  parts <- c(paste0("SDRF-Proteomics field (", hit$sdrf_requirement[1], "; ",
                    hit$status[1], "). Value: ", hit$value_or_reason[1], "."))
  if (!is.na(hit$why_missing[1]) && nzchar(hit$why_missing[1])) {
    parts <- c(parts, paste0("Missing because: ", hit$why_missing[1], "."))
  }
  if (!is.na(hit$notes[1]) && nzchar(hit$notes[1])) {
    parts <- c(parts, hit$notes[1])
  }
  paste(parts, collapse = " ")
}

rows <- list()
undocumented <- character(0)
for (t in TABLES) {
  p <- rel(dirname(t), basename(t))
  if (!file.exists(p)) {
    stop("Release table missing when building the dictionary: ", t, call. = FALSE)
  }
  cols <- names(read_release(p))
  cols <- cols[nzchar(trimws(cols))]
  if (t == "pride/sdrf.tsv") {
    for (cn in cols) {
      d <- sdrf_description(cn)
      if (is.na(d)) undocumented <- c(undocumented, paste0(t, " :: ", cn))
      rows[[length(rows) + 1L]] <- data.frame(table = t, column = cn, description = d,
                                              stringsAsFactors = FALSE, check.names = FALSE)
    }
    next
  }
  if (t %in% WIDE) {
    rows[[length(rows) + 1L]] <- data.frame(
      table = t, column = "protein_group_id",
      description = unname(DESCRIPTIONS[["protein_group_id"]]),
      stringsAsFactors = FALSE, check.names = FALSE)
    rows[[length(rows) + 1L]] <- data.frame(
      table = t, column = "<one column per sample>",
      description = unname(WIDE_NOTE[[t]]),
      stringsAsFactors = FALSE, check.names = FALSE)
    next
  }
  for (cn in cols) {
    d <- if (cn %in% names(DESCRIPTIONS)) unname(DESCRIPTIONS[[cn]]) else NA_character_
    if (is.na(d)) undocumented <- c(undocumented, paste0(t, " :: ", cn))
    rows[[length(rows) + 1L]] <- data.frame(table = t, column = cn, description = d,
                                            stringsAsFactors = FALSE, check.names = FALSE)
  }
}
if (length(undocumented)) {
  stop("Columns with no data-dictionary entry:\n",
       paste("  -", unique(undocumented), collapse = "\n"), call. = FALSE)
}
dictionary <- do.call(rbind, rows)
rownames(dictionary) <- NULL
release_log("  data dictionary: ", nrow(dictionary), " column definitions over ",
            length(TABLES), " tables")

# --------------------------------------------------------------------------------------
# README_DATA.md
# --------------------------------------------------------------------------------------

n_with_hits <- sum(as.integer(diff_summary$n_significant_fdr_0_05) > 0L)
mch <- diff_summary[diff_summary$canonical_comparison ==
                      "mcherry_paired_veh_over_mcherry_unpaired_veh", , drop = FALSE]

R <- c(
"# Associative Memory Proteomics -- publication data package",
"",
"Animal-level proteomics of four dissected fractions from a chemogenetic associative-memory",
"experiment. This package contains the processed data, the differential and enrichment",
"results, the manuscript figure source data, and the metadata needed to interpret and",
"redeposit them.",
"",
"**Read this first:** the independent experimental unit is the **animal**, not the",
"hemisphere. An earlier version of this analysis treated left and right hemispheres as",
"independent replicates. That was pseudoreplication and has been corrected throughout. See",
"`editor_source_data/REVISION_PROTEOMICS_DATA_CHANGELOG.md` for what changed.",
"",
"---",
"",
"## 1. Experimental design",
"",
"12 mice. From each animal, four fractions were collected from each hemisphere:",
"",
"| Sample class | Historical alias | What it is |",
"|---|---|---|",
"| `mcherry` | `mCherryN` | mCherry-labelled fraction |",
"| `neuropil` | `bg` / `Background` | neuropil compartment -- **not** a blank, negative control or background subtraction |",
"| `cfos` | `cFosN` | cFos-labelled fraction |",
"| `neuron` | `neuron` | neuronal fraction |",
"",
"Each animal is in exactly one of four conditions:",
"",
"| Code | Condition | Pairing | Treatment |",
"|---|---|---|---|",
"| 1 | `paired_cno` | paired | cno |",
"| 2 | `paired_veh` | paired | veh |",
"| 3 | `unpaired_cno` | unpaired | cno |",
"| 4 | `unpaired_veh` | unpaired | veh |",
"",
"12 animals x 4 sample classes x 2 hemispheres = **96 acquisition measurements**.",
"3 animals per condition, so **n = 3 animals** in every condition x sample class stratum,",
"with complete left/right pairing in all 16 strata.",
"",
"## 2. The statistical unit correction",
"",
"Left and right measurements were averaged with equal weight within each",
"`AnimalID x sample_class` unit, on the existing imputed log2 values, **before any",
"statistical test**. 96 measurements become **48 animal-level units**.",
"",
"In a balanced design the mean of animal means equals the mean of all hemispheres, so point",
"estimates barely move. What changes is the inference: standard errors, degrees of freedom",
"and every p-value.",
"",
"## 3. Measurement-level versus animal-level data",
"",
"| File | Shape | Use it for |",
"|---|---|---|",
"| `processed_data/protein_abundance_measurement_level.tsv.gz` | 5,349 x 96 | acquisition-level QC only |",
"| `processed_data/protein_abundance_animal_level.tsv.gz` | 5,349 x 48 | **all inference** |",
"",
"### The value scale, and what the effect size therefore means",
"",
"**These matrices are standardised per protein, not log2 abundance.** Measured directly",
"from the data: every protein has mean 0 and standard deviation 1 across the 96",
"acquisitions. The build asserts this and refuses to run if it ever stops holding.",
"",
"The consequence matters for reading the results. ProTigy reports its effect size as",
"`logFC`, and the canonical split tables call it `log2fc`, but a difference of group means",
"on a per-protein standardised scale is a **standardised mean difference in units of",
"per-protein standard deviation** -- not a log2 ratio. An effect size of 2 means \"two",
"per-protein standard deviations\", not \"four-fold\". This package therefore publishes the",
"column as `effect_size_sd_units`, with `effect_size_definition` and",
"`effect_size_source_column` on every row, rather than propagating a fold-change reading",
"the data do not support.",
"",
"Corroboration: `average_standardized_abundance` (limma `AveExpr`) lies within +/-0.0011 of",
"zero for all 5,349 proteins, which is only possible on a per-protein centred input.",
"",
"The upstream reason for the standardisation is **not documented** -- see section 15. The",
"nearest thing to a record is a sibling file at the project root named",
"`pg.matrix_filtered_70percent-onegroup_imputed_ANOVA_z-scored.txt`, whose values match",
"this matrix to within rounding (identical protein order, 96 identical sample columns,",
"maximum absolute difference 0.005 -- the signature of a 2-decimal serialisation). Its",
"filename is consistent with what the numbers show, but a filename is not a processing",
"record, and the matrix in use is named `pcaAdjusted_unnormalized`, which is consistent",
"with neither.",
"",
"Do not run inference on the measurement-level matrix. It is provided because two",
"supplementary QC panels legitimately need the acquisition as their unit (hemisphere and",
"collection-plate QC cannot be shown at animal level, because neither variable exists in",
"the 48-row metadata).",
"",
"Neither file is raw mass-spectrometry data. See section 20.",
"",
"## 4. The 12 primary contrasts",
"",
"4 sample classes x 3 within-sample-class contrast families:",
"",
"1. `paired_cno` vs `paired_veh` -- chemogenetic effect in paired animals",
"2. `paired_veh` vs `unpaired_veh` -- pairing-associated (learning) signature",
"3. `unpaired_cno` vs `unpaired_veh` -- chemogenetic effect in unpaired controls",
"",
"All 12 are in `metadata/primary_contrast_manifest.tsv`. Positive log2FC always means",
"higher in the numerator condition.",
"",
"## 5. Secondary analyses",
"",
"Kept in a separate file, `metadata/secondary_analysis_manifest.tsv`, and never mixed into",
"the primary table: the Supplementary E cross-compartment within-animal paired model, the",
"log2FC-ranked GSEA sensitivity analysis, the post-hoc Pairing x CNO interaction, the EWCE",
"baseline analysis, and two candidate contrasts that were deliberately not analysed.",
"",
"## 6. Differential statistics",
"",
"`differential_analysis/primary_differential_proteins.tsv.gz` -- one row per protein group",
"per comparison, 12 x 5,349 = 64,188 rows. Within-sample-class two-sample moderated t",
"(ProTigy), 3 vs 3 animals. Benjamini-Hochberg FDR.",
"",
"Two protein counts appear throughout and mean different things:",
"",
"- **5,349** protein groups were tested.",
"- **5,327** carry a mouse identifier and could be annotated and used for enrichment. The",
"  22-row difference is non-mouse contaminant entries (human keratins, porcine trypsin).",
"  The manuscript figures were drawn from the 5,327 set, so both counts are reported side",
"  by side in `primary_differential_summary.tsv`.",
"",
sprintf(paste("Of the 12 primary comparisons, %d contain at least one FDR-significant protein",
              "and %d contain none."), n_with_hits, 12L - n_with_hits),
"",
"## 7. GSEA",
"",
"**Canonical GSEA ranks by the moderated t statistic.** log2FC-ranked GSEA is a sensitivity",
"analysis only and lives in `enrichment/GSEA_log2FC_sensitivity.tsv.gz` with",
"`analysis_role = sensitivity` on every row. Never pool the two.",
"",
"Settings: GO-BP and KEGG, minGSSize 10, maxGSSize 800, BH adjustment, `pvalue_cutoff = 1`",
"and `qvalue_cutoff = 1` -- so the exported tables hold **every tested term**, not a",
"significant-only subset. Filter on `adjusted_p_value` yourself.",
"",
"## 8. ORA universe",
"",
"All unique successfully mapped measured UniProt accessions, computed per comparison. Four",
"query-list variants are exported and distinguished by the `query_list` column: all",
"FDR-significant proteins, FDR-significant higher in the numerator, FDR-significant higher",
"in the denominator, and an alternative list defined by absolute log2FC.",
"",
"Where a comparison had no FDR-significant proteins there is no query list and hence no ORA",
"rows. `enrichment/enrichment_coverage.tsv` records every such block explicitly, so an",
"absent block reads as a result and not as a missing file.",
"",
"## 9. Identifier mapping",
"",
"UniProt `MOUSE_10090_idmapping.dat`, snapshot 2025-11-03, plus 11 hand-curated overrides.",
"Both are hashed in `provenance/software_versions.tsv` and",
"`processed_data/protein_feature_annotation.tsv.gz`.",
"",
"**Field naming.** The internal pipeline carries a column named `gene_symbol` that actually",
"holds a UniProt identifier -- a UniProt entry name in the split tables and a UniProt",
"accession in the mapped tables. That name is **not** used in this package. Here:",
"",
"| Published column | Holds | Example |",
"|---|---|---|",
"| `protein_group_id` | UniProt entry name(s) | `MFA1A_MOUSE;MFA1B_MOUSE` |",
"| `protein_group_uniprot_accessions` | all accessions in the group | `C0HKD8;C0HKD9` |",
"| `uniprot_accession` | leading accession | `C0HKD8` |",
"| `gene_symbol` | resolved gene symbol | `Mfap1a` |",
"| `gene_symbols_in_group` | all symbols in the group | `Mfap1a;Mfap1b` |",
"| `protein_description` | real protein description | `Microfibrillar-associated protein 1A` |",
"",
"## 10. EWCE",
"",
"`enrichment/primary_EWCE.tsv.gz`. Bootstrap cell-type enrichment, 10,000 replicates,",
"measured-proteome background of 4,859. Primary setting: annotation level 2, top-N 250,",
"global FDR 0.05; other top-N and annotation-level settings are exported with",
"`analysis_role = sensitivity`. The cell-type reference is `ewceData::ctd()`.",
"",
"Note: an `l1_amygdala.loom` single-cell file exists in the project inputs but is **not**",
"used by the canonical EWCE run, and it is not evidence about which brain region was",
"dissected.",
"",
"## 11. PCA",
"",
"Animal-level PCA over all 5,349 proteins and 48 units, 0 zero-variance rows removed.",
"PC1 29.1%, PC2 20.5%, PC3 12.1%. Acquisition-level PCA is retained only for the two",
"technical QC panels.",
"",
"## 12. Figure source data",
"",
"`editor_source_data/figure_source_map.tsv` maps every manuscript proteomics panel to the",
"release table, row filter, statistical unit and generating script behind it. The per-panel",
"source-data files are copied byte-for-byte into",
"`editor_source_data/figure_source_data/`.",
"",
"## 13. Known design limitations",
"",
if (nrow(discrepancy) > 0L) c(
sprintf(paste("- **UNRESOLVED SAMPLE-CLASS DISCREPANCY, %d of 96 measurements.** The sample",
              "class used by the validated analysis (from `sample_info.xlsx`) is",
              "contradicted, for these %d acquisitions, by BOTH independent records: the",
              "`group_label` column of `sample_annotation.xlsx`, and the autosampler plate",
              "layout that the other 90 measurements follow. The two independent sources",
              "agree with each other on all %d."),
        nrow(discrepancy), nrow(discrepancy), nrow(discrepancy)),
paste0("  Affected: animals ",
       paste(sort(unique(discrepancy$AnimalID)), collapse = " and "),
       ", left hemisphere only, sample classes ",
       paste(sort(unique(discrepancy$sample_class_used_by_analysis)), collapse = ", "),
       ". The pattern is a one-row shift within each animal, so the three classes are",
       " cyclically permuted."),
paste0("  This has NOT been corrected here. Correcting it would change the animal-level",
       " aggregation and therefore every downstream result, which is out of scope for a",
       " packaging step. It is published as a documented discrepancy in",
       " `metadata/sample_class_source_discrepancy.tsv`, and `sample_class_corroborated`",
       " in `metadata/sample_metadata.tsv` flags every affected row."),
paste0("  **A decision from the experimenter is required before publication.** ",
       nrow(discrepancy), " of 48 animal-level units are affected: ",
       paste(sort(unique(discrepancy$animal_level_unit_affected)), collapse = ", "), ".")
) else
"- Sample class is corroborated by two independent sources for all 96 measurements.",
"- **n = 3 animals per group.** Small, and the corrected analysis reflects that.",
"- **The mCherry learning result is unresolved.** ",
sprintf(paste("  It retains %s FDR-significant proteins of %s mapped, but the shift is broad",
              "and one-directional with no GSEA or ORA pathway coherence, and no technical",
              "batch metadata exist. Neither a biological nor a technical explanation is",
              "established."),
        mch$n_significant_fdr_0_05_mapped_only, mch$n_proteins_tested_mapped_only),
"- **Figures 3 H and 3 I compare contrasts that share an arm.** Both contain `paired_veh`,",
"  on opposite sides, so the observed opposition is forced by the design. Descriptive only.",
"- **Supplementary E is a secondary paired model** with residual df 6 before moderation.",
"- **No acquisition-level technical QC beyond identification counts.** The QC report for",
"  this acquisition was never produced for this project.",
"",
"## 14. Collection plate",
"",
PLATE_SENTENCE,
"",
NO_BATCH_SENTENCE,
"",
"The `Plate1`/`Plate2` token records **which plate a sample was collected onto**. It is not",
"a proteomics preparation, digestion, LC-MS, acquisition or instrument batch, and no such",
"batch metadata exist for this dataset. 11 of 12 animals follow paired -> Plate1 /",
"unpaired -> Plate2, and in the learning contrast the association is complete in every",
"sample class. At acquisition level, collection plate explains 0.01% of PC1 and 1.5% of",
"PC2, neither significant.",
"",
"## 15. Upstream preprocessing limitation",
"",
"The reproducible pipeline **starts** at the 5,349 x 96 processed matrix. The steps that",
"produced it from the 5,747-row search output -- filtering, log transformation,",
"normalisation, imputation and PCA adjustment -- are **not reproducible from this",
"repository**: no producing script survives, no seed was recorded for the stochastic",
"imputation, and the search-software output is absent from the project. The processed",
"matrix should be treated as a given input, cited by its SHA256.",
"",
"Full account: `provenance/UPSTREAM_PREPROCESSING_GAP.md`.",
"",
"## 16. Provenance and integrity",
"",
"| File | What it gives you |",
"|---|---|",
"| `provenance/data_lineage.tsv` | every artefact from acquisition to release, with unproven edges marked `UNRESOLVED` |",
"| `provenance/software_versions.tsv` | exact versions as recorded by the runs themselves, or `UNKNOWN` with the source that would supply them |",
"| `provenance/analysis_parameters.tsv` | every recorded analysis parameter |",
"| `provenance/release_manifest.tsv` | per-file role, shape, SHA256, source artefact and generating script |",
"| `provenance/SHA256SUMS.txt` | checksums for the whole package |",
"| `provenance/sessionInfo_release.txt` | the environment that built the package |",
"",
"Two upstream artefacts are locked by hash and verified at build time:",
"",
"```",
"animal-level matrix  f12cf99e1bfb7c17bbf56bffb6783e924698bce5d5533a8e312bc4bbb733bbb3",
"ProTigy statistics   e1ae20f02e2747cfae3572933f2b23e6c770b92ef6810963a2806afb7adbe2b6",
"```",
"",
"## 17. How this package maps to PRIDE",
"",
paste0("Current status: **`", pride_status, "`**."),
"",
"The 96 native acquisition files are `.d` directories. Their names are known for all 96 and",
"appear in `metadata/sample_metadata.tsv` (`raw_file_basename`) and `pride/sdrf.tsv`",
"(`comment[data file]`), but **the files themselves are not in this package and were not",
"found anywhere in the project tree**.",
"",
paste0("`pride/sdrf.tsv` follows SDRF-Proteomics conventions as far as the verified metadata",
       " allow. ", n_required_missing, " SDRF-required fields could not be populated from",
       " any file in the project and carry `not available`; each is itemised in",
       " `pride/SDRF_MISSING_METADATA.md` with the document that would supply it."),
"",
"No acquisition metadata was inferred. Instrument model, digestion enzyme, DIA acquisition",
"method, search-software version, labelling chemistry, database-search parameters, the",
"dissected brain region, animal sex and animal age are all recorded as missing rather than",
"guessed.",
"",
"## 18. Package layout",
"",
"```",
"README_DATA.md",
"metadata/         sample and animal-level metadata, contrast manifests, data dictionary",
"processed_data/   abundance matrices and protein feature annotation",
"differential_analysis/  the 12 primary comparisons, long format",
"enrichment/       GSEA, ORA, EWCE, sensitivity, coverage and run parameters",
"editor_source_data/  the source-data workbook, changelog, figure map and panel data",
"pride/            SDRF and deposition notes",
"provenance/       lineage, versions, parameters, manifest and checksums",
"```",
"",
"## 19. Column definitions",
"",
"`metadata/data_dictionary.tsv` describes every column of every table in this package. It",
"is generated by walking the tables, and the build fails if a column has no definition.",
"",
"## 20. What is not here",
"",
"Native raw mass-spectrometry data. In particular, the file supplied with the original",
"submission as `processed_protein_group_matrix_raw.txt` is **not** raw mass-spectrometry",
"data: it is a 5,747-row protein-group matrix from the search software. See",
"`pride/README_PRIDE.md`.",
"",
"---",
"",
paste0("Generated by `", STAGE, "`."),
""
)
release_check_forbidden_wording(R)
if (!any(grepl(PLATE_SENTENCE, paste(R, collapse = " "), fixed = TRUE))) {
  stop("The required collection-plate sentence is not present verbatim in README_DATA.md.",
       call. = FALSE)
}
release_write_lines(R, release_path("README_DATA.md"))
release_log("  wrote README_DATA.md (", length(R), " lines); wording checks pass")

w <- release_write_table(dictionary, release_path("metadata", "data_dictionary.tsv"))
release_register("metadata/data_dictionary.tsv",
                 "definition of every column in every release table",
                 "all release tables", NA_character_, STAGE, "tsv")
release_register("README_DATA.md", "human entry point to the publication data package",
                 "all release tables", NA_character_, STAGE, "md")
release_log("  wrote data_dictionary.tsv (", w$rows, "x", w$cols, ")")
release_log("stage 11 complete")
